name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13
    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false

    - name: Run unittest tests
      run: poetry run python -m unittest discover -s tests